"""add document status

Revision ID: 8a6b8ec48778
Revises: 196d92004c77
Create Date: 2026-08-13 22:59:38.810481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8a6b8ec48778'
down_revision: Union[str, Sequence[str], None] = '196d92004c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
